### ISSUE TITLE
Unable to Run doPost()

### ISSUE THREAD

**Issue by nlahn7** [william-reed/GroupMe-Bots-With-Google-Apps-Script#10]
Hello, 
I followed all the instructions given in your README feel, but when I tried to run the doPost() method to authorize the script I get the following error:
TypeError: Cannot read property "postData" from undefined. (line 10, file "Code")

If you have any idea on how to fix this it would be greatly appreciated, thank you!

**Comment by william-reed** [comment]
Are you trying to run doPost() directly from Google Apps Script editor? Or are you triggering it from the group chat?

**Comment by nlahn7** [comment]
I was able to figure out the issue. Thank you!

**Comment by pablitonadal** [comment]
I have the same problem:

"TypeError: Cannot read property 'postData' of undefined (riga 5, file "Codice")"

can I ask you how did you solve it? 
Can you help me? Please.

Thank you.

**Comment by frae91** [comment]
Also running in circles with postData. Care to share the fix?

**Comment by william-reed** [comment]
@pablitonadal @frae91 have you guys both followed the basic guide from https://github.com/william-reed/GroupMe-Bots-With-Google-Apps-Script/wiki/Deploying-and-Using-a-Google-Apps-Script? are you running into this error in response to a message callback or when calling this method directly some other way?

**Comment by frae91** [comment]
There must be a typo somewhere, got it running already. Thanks!

**Comment by mvbuccheri** [comment]
Hi I'm trying this out too, what was the fix? I'm running into the same issue

**Comment by william-reed** [comment]
@mvbuccheri have you followed the basic guide from https://github.com/william-reed/GroupMe-Bots-With-Google-Apps-Script/wiki/Deploying-and-Using-a-Google-Apps-Script? are you running into this error in response to a message callback or when calling this method directly some other way?
